### ISSUE TITLE
Generate G1X and G2X commands without feedrate

### ISSUE THREAD

**Issue by ronangaillard** [Strooom/GRBL-Post-Processor#11]
In GRBL 1.1 feedrate is mandatory when sending G1X or G2X commands. Here are errors I get after with Gcode generated by GRBL-Post-Processor

GRBL 1.1 will return error 22 if using GRBL-Post-Processor.

**Comment by Strooom** [comment]
at the beginning of each section, the feedrate output is reset, so the postProcessor should output the F word correctly. This is nothing new for GRBL1.1, it was always like that. A G1, G2, G3 move doesn't make sense if there is not a feedrate defined upfront..
