### ISSUE TITLE
Preferred post processor?

### ISSUE THREAD

**Issue by JimF42** [Strooom/GRBL-Post-Processor#16]
I see that you have two post processors, f360-easel.cps and OpenbuildsGRBL.cps.

Which is the preferred one for using with an X-Controller (GRBL 1.1) and UGS (not Easel) as my sender?

Thanks,
Jim

**Comment by Strooom** [comment]
OpenbuildsGRBL.cps is the one.
the f360easel.cps is just there for me as a resource for reverse engineering.

Please note the I ony tested up to GRBL 0.9, and that a minor issue has been introduced by a co-author, which needs to be looked at in-depth.
