### ISSUE TITLE
Tool-rotation error

### ISSUE THREAD

**Issue by darrepac** [Strooom/GRBL-Post-Processor#23]
Hi

I have a tool rotation error while I have selected a 3axis standard machine in Fusion 360.

> Error: Fatal Error in Operation 1: Tool-Rotation detected but GRBL only supports 3 Axis

> Error` at line: 671

> Error in operation: 'Circular1'

Where can I look at to check or change something?

**Comment by darrepac** [comment]
Ok in case someone land here with the same problem.
You have to avoid to use tool orientation but change the WCS

**Comment by Strooom** [comment]
It means you are doing stuff in Fusion360, which cannot be executed by GRBL afterwards. So don't use 5-axis stuff in Fusion. Stick to 3 or 2.5 axis CAM.
