### ISSUE TITLE
grbl-post-processor ? Solidworks

### ISSUE THREAD

**Issue by quotelawrence** [Strooom/GRBL-Post-Processor#24]
is there a module for Solidworks to use grbl ctl. files, my question will this work in solidworks ?

**Comment by Strooom** [comment]
I'm sorry, I don't know. 
I know the CAM part of Fusion360 is originating from a 3rd party (I think HSM Works) and it could be used in other CAD software. But I don't have Solidworks to try it out. You should try for yourself, little harm can be done.
